extends:
  - uphold

globals:
  artifacts: true

rules:
  id-length: 0
  id-match:
    - error
    - '^_$|^[\$_a-zA-Z]*[_a-zA-Z0-9]*[a-zA-Z0-9]*$|^[A-Z][_A-Z0-9]+[A-Z0-9]$'
    - onlyDeclarations: true
      properties: true
  max-params: 0
  no-constant-condition: 0
  no-underscore-dangle:
    - error
    - allow:
      - __class__
      - super_
